### ISSUE TITLE
Does this work with il2cpp on android?

### ISSUE THREAD

**Issue by friuns2** [BepInEx/HarmonyX#34] opened 2021-10-12 08:51 UTC
Hello, does Method patching work with il2cpp on android? About page a bit unclear about it.

**Comment by ghorsington** [comment] 2021-10-12 08:58
It is indeed unclear about it because it was never tested. Technically MonoMod (the backend we use for patching) supports ARM targets, so it could be possible.

For Il2Cpp support, you'll need to implement [a method patcher backend](https://github.com/BepInEx/HarmonyX/wiki/Custom-MethodPatcher) as there isn't one included for Il2Cpp.

**Comment by friuns2** [comment] 2021-10-12 09:21
Hi Thanks i could test it, but I can't find BepInEx.IL2CPP.Hook.IL2CPPDetourMethodPatcher, i downloaded BepInEx.dll from release page but still can't the namespace.   
  
 

![](https://user-images.githubusercontent.com/16543239/136928771-476ab4e3-a8db-4804-9b6a-b9bd39c3e617.png)

**Comment by friuns2** [comment] 2021-10-12 18:02
What do you mean by x86 will it work on android arm7 or arm64? Also i see IL2CPPDetourMethodPatcher.cs have il.Emit() which cannot run on il2cpp platform, will method detour work without them like swap pointers in vTable?    
  
I would like to run method detour inside game to replace methods with nlua 

For example this library doing hooks without il.Emit but it not work on android https://github.com/Misaka-Mikoto-Tech/MonoHook/

**Comment by ghorsington** [comment] 2021-10-16 10:04
Closing as resolved, since the main question was about Il2Cpp. Moreover, HarmonyX is not usable in the case OP needed (HarmonyX compiled with Il2Cpp) as HarmonyX was intended to be instead used via mono runtime or CoreCLR injected into Il2Cpp (e.g. BepInEx).

**Closed as completed by ghorsington** 2021-10-16 10:04 UTC
